project_name: glouton
snapshot:
  # Our version is based on the date.
  name_template: '{{ time "06.01.02.150405" }}'
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - 386
  goarm:
  - 6
  ignore:
  - goos: windows
    goarch: arm
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: binary
nfpms:
- vendor: Bleemeo
  homepage: https://bleemeo.com
  maintainer: "Bleemeo Packaging Team <jenkins@bleemeo.com>"
  recommends:
  - sudo
  - ca-certificates
  - net-tools
  - cron
  description: |
    Bleemeo agent
      Bleemeo is a solution of Monitoring as a Service.
      This package contains the agent which send metric to
      the SaaS platform
  license: Apache 2.0
  formats:
  - deb
  - rpm
  bindir: /usr/sbin
  files:
    "packaging/common/glouton.service": "/lib/systemd/system/glouton.service"
    "packaging/common/glouton-hook-package-modified": "/usr/lib/glouton/glouton-hook-package-modified"
    "bin/glouton-netstat": "/usr/sbin/glouton-netstat"
    "bin/glouton-gather-facts": "/usr/sbin/glouton-gather-facts"
  config_files:
    "etc/glouton.conf": "/etc/glouton/glouton.conf"
    "packaging/common/glouton-05-system.conf": "/etc/glouton/conf.d/05-system.conf"
    "packaging/common/glouton.sudoers": "/etc/sudoers.d/glouton"
    "packaging/common/glouton.cron.hourly": "/etc/cron.hourly/glouton"
  empty_folders:
  - /etc/glouton/conf.d
  - /var/lib/glouton
  scripts:
    postinstall: "packaging/scripts/postinstall.sh"
    preremove: "packaging/scripts/preremove.sh"
    postremove: "packaging/scripts/postremove.sh"
  overrides:
    deb:
      config_files:
        "packaging/deb/glouton-06-distribution.conf": "/etc/glouton/conf.d/06-distribution.conf"
        "packaging/deb/glouton.apt.conf": "/etc/apt/apt.conf.d/05glouton"
    rpm:
      recommends:
      - yum-plugin-post-transaction-actions
      config_files:
        "packaging/rpm/glouton.yum.action": "/etc/yum/post-actions/glouton.action"
        "packaging/rpm/glouton-06-distribution.conf": "/etc/glouton/conf.d/06-distribution.conf"
        "packaging/rpm/glouton-dnf-plugin.py": "/usr/lib/python3.6/site-packages/dnf-plugins/glouton.py"
dockers:
- image_templates:
  - glouton:latest
  - glouton:{{.Version}}
  extra_files:
  - etc/glouton.conf
  - packaging/docker/60-glouton.conf
  - packaging/common/glouton-05-system.conf
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Don't try to modify Github
  disable: true
