project_name: glouton
snapshot:
  # Our version is based on the date.
  name_template: '{{ time "06.01.02.150405" }}'
builds:
- env:
  - CGO_ENABLED=0
  targets:
  - linux_amd64
  - linux_386
  - linux_arm_6
  - linux_arm64
  - windows_amd64
  - windows_386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: binary
nfpms:
- vendor: Bleemeo
  homepage: https://bleemeo.com
  maintainer: "Bleemeo Packaging Team <jenkins@bleemeo.com>"
  recommends:
  - sudo
  - ca-certificates
  - net-tools
  - cron
  description: |
    Bleemeo agent
      Bleemeo is a solution of Monitoring as a Service.
      This package contains the agent which sends metrics to
      the SaaS platform.
  license: Apache 2.0
  formats:
  - deb
  - rpm
  bindir: /usr/sbin
  contents:
  # Files
  - src: packaging/common/glouton.service
    dst: /lib/systemd/system/glouton.service
  - src: packaging/common/glouton-hook-package-modified
    dst: /usr/lib/glouton/glouton-hook-package-modified
  - src: bin/glouton-netstat
    dst: /usr/sbin/glouton-netstat
  - src: bin/glouton-gather-facts
    dst: /usr/sbin/glouton-gather-facts
  - type: dir
    dst: /etc/glouton/conf.d
  - type: dir
    dst: /var/lib/glouton
  # Global config files
  - src: etc/glouton.conf
    dst: /etc/glouton/glouton.conf
    type: config
  - src: packaging/common/glouton-05-system.conf
    dst: /etc/glouton/conf.d/05-system.conf
    type: config
  - src: packaging/common/glouton.sudoers
    dst: /etc/sudoers.d/glouton
    type: config
  - src: packaging/common/glouton.cron.hourly
    dst: /etc/cron.hourly/glouton
    type: config
  # Debian config files
  - src: packaging/deb/glouton-06-distribution.conf
    dst: /etc/glouton/conf.d/06-distribution.conf
    type: config
    packager: deb
  - src: packaging/deb/glouton.apt.conf
    dst: /etc/apt/apt.conf.d/05glouton
    type: config
    packager: deb
  # RPM config files
  - src: packaging/rpm/glouton.yum.action
    dst: /etc/yum/post-actions/glouton.action
    type: config
    packager: rpm
  - src: packaging/rpm/glouton-06-distribution.conf
    dst: /etc/glouton/conf.d/06-distribution.conf
    type: config
    packager: rpm
  - src: packaging/rpm/glouton-dnf-plugin.py
    dst: /usr/lib/python3.6/site-packages/dnf-plugins/glouton.py
    type: config
    packager: rpm
  scripts:
    postinstall: "packaging/scripts/postinstall.sh"
    preremove: "packaging/scripts/preremove.sh"
    postremove: "packaging/scripts/postremove.sh"
  overrides:
    rpm:
      recommends:
      - sudo
      - ca-certificates
      - net-tools
      - cron
      - yum-plugin-post-transaction-actions

dockers:
- image_templates:
  - glouton:latest
  - glouton:{{.Version}}
  extra_files:
  - etc/glouton.conf
  - packaging/docker/60-glouton.conf
  - packaging/common/glouton-05-system.conf
  - packaging/kubernetes/glouton-k8s-default.conf
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Don't try to modify Github
  disable: true
