project_name: glouton
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - 386
  goarm:
  - 6
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: binary
dockers:
- image_templates:
  - glouton:latest
  - glouton:{{.Version}}
  extra_files:
  - 60-bleemeo.conf
  - packaging/common/bleemeo-05-system.conf
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ time "06.01.02.150405" }}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Don't try to modify Github
  disable: true
