---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: glouton
spec:
  selector:
    matchLabels:
      app: glouton
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: glouton
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      hostPID: true
      containers:
      - image: bleemeo/bleemeo-agent:{{ .Chart.AppVersion }}
        name: glouton
        ports:
        - name: http
          containerPort: 8015
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-glouton
          mountPath: /var/lib/glouton
        - name: hostroot
          mountPath: /hostroot
          readOnly: true
        # We used another folder than "conf.d" because we want to merge existing
        # file from conf.d and file coming from Kubernetes glouton-config.
        - name: glouton-config
          mountPath: /etc/glouton/conf-k8s.d/
        env:
        - name: GLOUTON_CONFIG_FILES
          value: "/etc/glouton/glouton.conf,/etc/glouton/glouton-k8s-default.conf,/etc/glouton/conf.d,/etc/glouton/conf-k8s.d"
        - name: GLOUTON_KUBERNETES_ENABLE
          value: "True"
        - name: GLOUTON_KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if eq .Values.config.bleemeo.enable true }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-credentials
        {{- end }}
        resources:
          requests:
            cpu: 0.05
            memory: 100Mi
      volumes:
      - name: lib-glouton
        hostPath:
          path: /var/lib/glouton
      # Note: glouton will use this hostPath to access Docker or containerd socket
      - name: hostroot
        hostPath:
          path: /
      - name: glouton-config
        configMap:
          name: {{ .Release.Name }}-config
