{{- if eq .Values.config.bleemeo.enable true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Values.namespace }}
type:
stringData:
  GLOUTON_BLEEMEO_ACCOUNT_ID: {{ required "account_id must be set" .Values.account_id }}
  GLOUTON_BLEEMEO_REGISTRATION_KEY: {{ required "registration_key must be set" .Values.registration_key }}
{{- end }}
