global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'glouton'
    static_configs:
    - targets: ['host.docker.internal:8016']
    params:
      noFilter: ['true']
