namespace: default

bleemeo:
  account_id: 
  registration_key:

# Add your custom configuration here.
# https://docs.bleemeo.com/agent/configuration
config:
  bleemeo:
    enable: true
  kubernetes:
    clustername: my_k8s_cluster_name
